extends:
  - standard
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"
  - n

parser: "@typescript-eslint/parser"
env:
  es2022: true
  node: true
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2022
  project: './tsconfig.json'
globals:
  describe: false
  it: false
  beforeEach: false
  afterEach: false
  beforeAll: false
  afterAll: false
  jasmine: false
  expect: false
rules:
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/no-explicit-any": "warn"